name: B21-workflow

on: workflow_dispatch

jobs:
  frist-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to git repo
        uses: actions/checkout@v7

      - name: setup node.js
        uses: action/setup-node@7
        with:
         node-version: 18


      - name: Install dependencies
        run: npm install
       
      - name: run test
        run: npm test
       
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: B21/app:latest    