name: B21-workflow

on: push

jobs: 
    first:
      runs-on: ubuntu-latest
      steps: 
        - name: print message
          run: echo "Hello guys how are you"

        - name: show content of /etc/passwd
          run : sudo cat /etc/passwd
        
        - name: show os details
          run : sudo cat /etc/od-release

        - name: show files
          run: sudo ls -l

