name: B21-workflow

on: push

jobs: 
    first:
      runs-on: ubuntu-latest
      steps: 
        - name: print message
          run: echo "Hello guys how are you"

    second-job:
      runs-on: ubuntu-latest
      steps:
        - name: print 2nd message for job
          run: echo "this is 2nd stage"

